#ifndef FUNCTIONSP2_HEADERSMACROSNAMESPACE_PRINT_ALIAS111_H
// ! Definition of our macros
#define FUNCTIONSP2_HEADERSMACROSNAMESPACE_PRINT_ALIAS111_H

#define Log(x) std::cout << x;
void printAlias();

#endif //FUNCTIONSP2_HEADERSMACROSNAMESPACE_PRINT_ALIAS111_H
